language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: heroku
  api_key:
    secure: levdQWcqf8PWKWHCuP2Xh5X78Ti522WKNtEofeuWK9EbYhqhTuBuOsE/9fLbuh7WWYItBfLEBfbNHe1M2nXhBDsfeorrdZkZlMM9AuD/bO6WojHbadwHH8sVX8OfiXwaKt37LsQP1eok+0d4cm34Ata4zOXcetQchED5V5uwuUa75bRun6z29pz3THMusXAZ3YzLdjrViUeQ0yV8rlZdRJtWGMKLg7lmRaigQXn/7ssdRE7wblNZhnzM3C09es9VB6dNqpFQlgty0F3gm7XB+HyTVD6bCcsUyCfvSYf6lssP6Zug8NaNEMW6zfIZyxQpcU1A95UfiAwHYsd7b2MZUGUzCSpISlRVQYpNNCU05G3Hd8WSJZX9tHKX7ReKXudeu/EAL4BpCYYiM5fO8agKkWKtBtrrNAG1aTtu62MJpUGWHAcOL2fm5onfIiboOG+/wDh+Glr7VG+0wKmxLoeofSrBy3ddWk3xiBr8VinMepHTjkXiWYOoJredfFEkWQuPBFdlt0lE4cXbEISn/kB9dN7FwPBzdb7y/1KfXg0CJBPnRAGl/P+CpusckwYw568A2vZXqHoifP07oxkj1WVEZaY0I0D/LTcXy3C1f1igvJ+aPZGojJHfZy2WWDjA8zAJ4TgqSXsKpBrJzVt9w1tViz2lDJz3iQWHs1aSjJZH67g=
  app: flask-static-2890
  on:
    repo: hallowf/GameSaveBackups-flask-static
