language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: heroku
  api_key:
    secure: GR9fFhtx6tRlGkTvDM5beVAnBY+TV66NPhgmD2tqtdkkxt3JfqwnVw0WC7XzWp5e39xJd04Rpd+cfmNUVvGXTPVzjv8NMwbIQuv1UPucgZMcwGdR6wqU7oz9H4SRp/cYo10ECWM6Yqa3tFOPDSQ5Tzp9vyWnMqERh88ReVyi1RQoMU8C+yVQN6Ip/pg+WS8zooCGQKg8qPtTlHrgAFaVaOfkzcLpsGcv+K2WOL40FbLCwnZCvDZarttURmIIslgUxcWYYbxwukm3YbQGmbhwWRQFjL9x0kxQ4JrkU0NApSIRtb4/BFL6gcziWoN4YUDvKITwZdSCvJG+VkCxsjSu0nH/MTw9/JrdqbDbSDmtGAmTjbCUkqtI3S0QGVtGSzltsf2DUqbZb8lhNZAjmBp3aSX8Ol8GKtct84iAInvIqDk9jMO3KGCzTAL0wRI/5GB21IV+dHCTfQtSy6BYj+oADg7qQI4U9GYNACSNSPy/6kU0J29kZJPGkz8qx7PWdYgsdFdDrd88QVdG2edyNTgONMpWLR0xcmdUNh9T5DyE/UdnRvHHPvRZgt7+S1CPon/Dy+cdNDZjm7qahmBrO9aJhY2Rr0f1NaapbXYj/u7VjAQyoeZXkoZnM0eBnR9DPCd3FF5lngKbOeuW/fnk6lS66AL5Wau3RkoPNynjJYUsvpQ=
  app: flask-static-2890
  on:
    repo: hallowf/GameSaveBackups
    branch: flask-static
